export const SET_EVENTS = "SET_EVENTS";
export const FETCH_EVENTS_FAILED = "FETCH_EVENTS_FAILED";

export const FETCH_EVENT_INIT = "FETCH_EVENT_INIT";
export const FETCHED_EVENT = "FETCHED_EVENT";
export const FETCH_EVENT_FAILED = "FETCH_EVENT_FAILED";

export const ADD_EVENT_INIT = "ADD_EVENT_INIT";
export const ADD_EVENT_SUCCESS = "ADD_EVENT_SUCCESS";
export const ADD_EVENT_FAILED = "ADD_EVENT_FAILED";

export const EDIT_EVENT_INIT = "EDIT_EVENT_INIT";
export const EDIT_EVENT_SUCCESS = "EDIT_EVENT_SUCCESS";
export const EDIT_EVENT_FAILED = "EDIT_EVENT_FAILED";

export const DELETE_EVENT_INIT = "DELETE_EVENT_INIT";
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const DELETE_EVENT_FAILED = "DELETE_EVENT_FAILED";
export const SELECT_TIME_START = "SELECT_TIME_START";
export const SELECT_TIME_FINISH = "SELECT_TIME_FINISH";

export const ADDING_START = "ADDING_START";
export const ADDING_FINISH = "ADDING_FINISH";

export const EDITING_START = "EDITING_START";
export const EDITING_FINISH = "EDITING_FINISH";

export const AUTH_INIT = "AUTH_INIT";
export const AUTH_CANCEL = "AUTH_CANCEL";
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
